site_name: pyown documentation
repo_name: pyown
site_url: https://jotonedev.github.io/pyown/
repo_url: https://github.com/jotonedev/pyown

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

    - navigation.tabs
    - navigation.tabs.sticky

    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

    - navigation.path
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  search:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
          - url: https://docs.python.org/3/objects.inv
            domains: [ py, std ]
        options:
          extensions:
            - griffe_inherited_docstrings
          members_order: source
          separate_signature: true
          filters: [ "!^_" ]
          canonical_version: "latest"
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          inherit_docstrings: true
          inherited_members: true
          show_source: false
          unwrap_annotated: true
          show_symbol_type_toc: true
          show_root_heading: true
          show_root_full_path: true
          show_inheritance_diagram: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          signature_crossrefs: true

markdown_extensions:
  - tables
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
      toc_depth: 3

  # Python markdown extensions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - API Reference:
      - Client: api/client.md
      - Messages: api/messages.md
      - Protocol: api/protocol.md
      - Tags: api/tags.md
      - Auth: api/auth.md
      - Exceptions: api/exceptions.md
      - Items:
          - Base: api/items/base.md
          - Lighting: api/items/lighting.md
          - Automation: api/items/automation.md
          - Gateway: api/items/gateway.md