site_name: PyOWN Documentation
site_url: https://jotonedev.github.io/pyown/
repo_url: https://github.com/jotonedev/pyown

theme:
    name: material
    palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo


plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true

