name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload release to PyPI'
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup and Cache Python Poetry
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: "3.12"
          poetry-version: "1.8.3"
          install-args: --all-extras

      - name: Package project
        run: poetry build

      - name: Sign build artifacts
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        if: ${{ (github.event.inputs.upload || github.event.action == 'published') && github.event.release.draft == false }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "dist/*"
